CREATE TABLE pointages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee VARCHAR(150) NOT NULL,
    file_url VARCHAR(500) NOT NULL
);

CREATE TABLE conges (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee VARCHAR(150) NOT NULL,
    file_url VARCHAR(500) NOT NULL
);


